spring:
  data:
    mongodb:
      username: haritha
      password: haritha
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090